#!/usr/bin/env node
/**
 * Packages the Node sidecar for a shipped desktop app.
 *
 * `tauri dev` can spawn `node sidecar/tool-host.mjs` because the developer has Node and the
 * workspace `node_modules` on disk. A shipped `.app`/`.msi`/`.AppImage` has neither, so this script
 * produces two self-contained artifacts under `sidecar/` that `tauri.conf.json` ships as
 * `bundle.resources` and `src-tauri/src/node.rs` resolves at runtime:
 *
 *   sidecar/dist/tool-host.cjs   — the sidecar + @newvector/core/node + docx/exceljs/pptxgenjs, rolled
 *                                  into one file by esbuild. No node_modules to resolve at runtime.
 *   sidecar/runtime/node[.exe]   — the *official* Node binary for the target platform, downloaded from
 *                                  nodejs.org and checksum-verified. Official builds are self-contained
 *                                  (ICU statically linked, only system libs), unlike a Homebrew/distro
 *                                  Node — so copying the local `process.execPath` would ship a runtime
 *                                  that fails on the user's machine. We download instead.
 *
 * Run via `pnpm --filter @newvector/desktop sidecar:bundle`. `tauri build`'s beforeBuildCommand runs
 * it automatically. Both artifacts are git-ignored — they are build outputs, regenerated per build.
 * The download is cached under `sidecar/.node-cache/` so repeat builds don't re-fetch.
 *
 * The runtime is staged for the *host* platform/arch, which is what Tauri builds for (the release
 * matrix runs one native runner per OS). Override with NEWVECTOR_RUNTIME_PLATFORM / _ARCH if needed.
 */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Pinned to a current LTS. Bump deliberately; the checksum is fetched from the matching SHASUMS256.txt.
const NODE_VERSION = "22.11.0";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const distDir = join(here, "dist");
const runtimeDir = join(here, "runtime");
const cacheDir = join(here, ".node-cache");

function log(msg) {
  process.stdout.write(`[sidecar:bundle] ${msg}\n`);
}

// --- 1. Build @newvector/core -------------------------------------------------------------------
// The bundle imports @newvector/core/node, whose package "exports" point at ./dist. esbuild resolves
// from that built output, so core must be compiled first. Idempotent and cheap; keeps this script
// runnable on its own (not just after a full workspace build).
log("building @newvector/core …");
execFileSync("pnpm", ["--filter", "@newvector/core", "build"], { cwd: repoRoot, stdio: "inherit" });

// --- 2. Bundle the sidecar into one self-contained file ----------------------------------------
log("bundling tool-host.cjs with esbuild …");
rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });
const outfile = join(distDir, "tool-host.cjs");
await build({
  entryPoints: [join(here, "tool-host.mjs")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  outfile,
  banner: { js: "// Generated by sidecar/build.mjs — do not edit." },
  logLevel: "warning",
});
log(`wrote ${outfile} (${(statSync(outfile).size / 1e6).toFixed(1)} MB)`);

// --- 3. Download + stage the official Node runtime ----------------------------------------------
const platform = process.env.NEWVECTOR_RUNTIME_PLATFORM || process.platform; // darwin | linux | win32
const arch = process.env.NEWVECTOR_RUNTIME_ARCH || process.arch; // arm64 | x64
const platTag = { darwin: "darwin", linux: "linux", win32: "win" }[platform];
if (!platTag) throw new Error(`Unsupported platform for Node runtime staging: ${platform}`);
if (arch !== "arm64" && arch !== "x64") throw new Error(`Unsupported arch for Node runtime staging: ${arch}`);

const ext = platform === "win32" ? "zip" : platform === "linux" ? "tar.xz" : "tar.gz";
const artifact = `node-v${NODE_VERSION}-${platTag}-${arch}`;
const archiveName = `${artifact}.${ext}`;
const baseUrl = `https://nodejs.org/dist/v${NODE_VERSION}`;
const nodeExe = platform === "win32" ? "node.exe" : join("bin", "node");
const cachedNode = join(cacheDir, artifact, nodeExe);

if (!existsSync(cachedNode)) {
  mkdirSync(cacheDir, { recursive: true });
  const archivePath = join(cacheDir, archiveName);

  log(`downloading ${archiveName} …`);
  const dl = await fetch(`${baseUrl}/${archiveName}`);
  if (!dl.ok) throw new Error(`Failed to download Node runtime (${dl.status}): ${baseUrl}/${archiveName}`);
  const bytes = Buffer.from(await dl.arrayBuffer());
  writeFileSync(archivePath, bytes);

  // Integrity: verify against the signed SHASUMS256.txt for this release. We ship this binary to
  // users, so a corrupted or tampered download must fail the build, not get packaged.
  log("verifying checksum …");
  const sumsRes = await fetch(`${baseUrl}/SHASUMS256.txt`);
  if (!sumsRes.ok) throw new Error(`Failed to fetch SHASUMS256.txt (${sumsRes.status})`);
  const sums = await sumsRes.text();
  const expected = sums.split("\n").map((l) => l.trim().split(/\s+/)).find(([, name]) => name === archiveName)?.[0];
  if (!expected) throw new Error(`No checksum for ${archiveName} in SHASUMS256.txt`);
  const actual = createHash("sha256").update(readFileSync(archivePath)).digest("hex");
  if (actual !== expected) throw new Error(`Checksum mismatch for ${archiveName}: expected ${expected}, got ${actual}`);

  // bsdtar (macOS/Windows 10+) and GNU tar (Linux) all extract .tar.gz/.tar.xz/.zip via `tar -xf`.
  log("extracting …");
  execFileSync("tar", ["-xf", archivePath, "-C", cacheDir], { stdio: "inherit" });
  rmSync(archivePath, { force: true });
  if (!existsSync(cachedNode)) throw new Error(`Node binary not found after extraction: ${cachedNode}`);
}

log("staging Node runtime …");
rmSync(runtimeDir, { recursive: true, force: true });
mkdirSync(runtimeDir, { recursive: true });
const stagedNode = join(runtimeDir, platform === "win32" ? "node.exe" : "node");
copyFileSync(cachedNode, stagedNode);
if (platform !== "win32") chmodSync(stagedNode, 0o755);
log(`staged ${artifact} -> ${stagedNode} (${(statSync(stagedNode).size / 1e6).toFixed(1)} MB)`);

log("done.");
